"""plan can_manage_templates

Revision ID: d4c49f63235c
Revises: 9c7abaf1781f
Create Date: 2026-01-30 19:44:44.792942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c49f63235c'
down_revision: Union[str, Sequence[str], None] = '9c7abaf1781f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_owner_user_id_fkey'), 'clients', type_='foreignkey')
    op.drop_column('clients', 'owner_user_id')
    op.add_column('plans', sa.Column('can_manage_templates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'can_manage_templates')
    op.add_column('clients', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('clients_owner_user_id_fkey'), 'clients', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###
